services:
  balance-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: balance-app
    ports:
      - "3000:80"
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - balance-network
networks:
  balance-network:
    driver: bridge
